#!/bin/bash
# set  -x
printf "\n##########################"
printf "\n##  Start Custom Build  ##"
printf "\n##########################"

VERSION="$(grep 'ARG VERSION=' Dockerfile | awk -F'=' '{ print $2 }' | tr -d '"' )"
printf "\nBuilding Context for Repo: %s" "$DOCKER_REPO"
printf "\n-- SOURCE_BRANCH	: %s" "$SOURCE_BRANCH"
printf "\n-- SOURCE_COMMIT	: %s (%s)" "$SOURCE_COMMIT" "$COMMIT_MSG"
printf "\n-- REPO_NAME 			: %s" "$REPO_NAME"
printf "\n-- IMAGE_NAME 		: %s (%s)" "$IMAGE_NAME" "$CACHE_TAG"
printf "\n-- UMURMUR VERSION: %s" "$VERSION"
printf "\n"
IMAGES2PUSH=""

buildUmurmur(){
	UMURMUR_VERSION="$1"
	SSL="$2"
	BUILD_NUMURMON="$3"
	BUILD_UMURMUR_MONITOR="$4"
	NAME="$5"
	NAME="${IMAGE_NAME}-${UMURMUR_VERSION}"
	if [[ "$3" == "On" ]] && [[ "$4" == "On" ]]; then
		NAME="$NAME-full"
	else 
		[[ "$3" == "On" ]] && NAME="$NAME-numurmon"
		[[ "$4" == "On" ]] &&	NAME="$NAME-monitor"
	fi
	printf "\n\n## Building %s ##\n" "$NAME"
	docker build --build-arg VERSION="$UMURMUR_VERSION" \
		--build-arg SSL="$SSL" \
		--build-arg BUILD_NUMURMON="$BUILD_NUMURMON" --build-arg BUILD_UMURMUR_MONITOR="$BUILD_UMURMUR_MONITOR" \
		-t "$NAME" . && IMAGES2PUSH="$NAME $IMAGES2PUSH" || (printf "\nCannot build %s" "$NAME"; exit 1)
}

if [[ "$SOURCE_BRANCH" =~ ^[0-9.]+$ ]]; then
	printf "\n##  Building Release %s" "$SOURCE_BRANCH"
else
	printf "\n##  Building test %s" "$SOURCE_BRANCH"
fi
buildUmurmur "$VERSION" "openssl" "Off" "Off" "$REPO_NAME:$SOURCE_BRANCH-$VERSION"
buildUmurmur "$VERSION" "openssl" "On" 	"Off" "$REPO_NAME:$SOURCE_BRANCH-$VERSION-numurmon"
buildUmurmur "$VERSION" "openssl" "Off" "On" 	"$REPO_NAME:$SOURCE_BRANCH-$VERSION-monitor"
buildUmurmur "$VERSION" "openssl" "On" 	"On" 	"$REPO_NAME:$SOURCE_BRANCH-$VERSION-full"
echo "$IMAGES2PUSH" > hooks/names
