#!/bin/bash
# set  -x

printf "\n#########################"
printf "\n##  Start Custom Push  ##"
printf "\n#########################"

while read line  
do  
  printf "\nPushing %s...\n" "$line"
	docker push "$line"
	if [[ "$SOURCE_BRANCH" =~ ^[0-9.]+$ ]] && [[ "$line" =~ .*-full ]]; then
		docker tag "$line" "${REPO_NAME}:latest"
		printf "\nPushing %s as %s...\n" "$line" "${REPO_NAME}:latest"
    docker push "${REPO_NAME}:latest"
	fi
done < hooks/names
