#!/bin/bash
# set  -x

printf "\n#########################"
printf "\n##  Start Custom Push  ##"
printf "\n#########################"

for i in $(cat hooks/names); do
	printf "\nPushing %s...\n" "$i"
	docker push "$i"
	if [[ "$SOURCE_BRANCH" =~ ^[0-9.]+$ ]] && [[ "$i" =~ .*-full ]]; then
		docker tag "$i" "${REPO_NAME}:latest"
		printf "\nPushing %s as %s...\n" "$i" "${REPO_NAME}:latest"
    docker push "${REPO_NAME}:latest"
	fi
done
